language: node_js

node_js:
  - "lts/*"

install: 
  - npm run install-client
  - npm run install-server

before_script:
  - npm run start-server
  - sleep 10

cache:
  directories:
    - node_modules

script:
  - npm run build-client
  - npm run test-client